# Generated by Django 5.1.4 on 2024-12-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_avatar',
            field=models.URLField(default='https://api.dicebear.com/7.x/avataaars/svg?seed=John'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
