# Generated by Django 5.1.4 on 2024-12-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author_avatar_blogpost_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_name',
        ),
    ]
